# Generated by Django 6.0.3 on 2026-03-14 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Continente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(help_text='Código de 2 letras (EU, AF, AS...)', max_length=2, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Continente',
                'verbose_name_plural': 'Continentes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_key', models.IntegerField(help_text='ID único de la especie en GBIF', unique=True)),
                ('scientific_name', models.CharField(help_text='Nombre científico completo', max_length=255)),
                ('canonical_name', models.CharField(blank=True, help_text='Nombre canónico sin autor ni año', max_length=255, null=True)),
                ('common_name', models.CharField(blank=True, help_text='Nombre común principal en español', max_length=255, null=True)),
                ('kingdom', models.CharField(blank=True, help_text='Reino', max_length=100)),
                ('phylum', models.CharField(blank=True, help_text='Filo', max_length=100)),
                ('class_name', models.CharField(blank=True, help_text='Clase', max_length=100)),
                ('order', models.CharField(blank=True, help_text='Orden', max_length=100)),
                ('family', models.CharField(blank=True, help_text='Familia', max_length=100)),
                ('genus', models.CharField(blank=True, help_text='Género', max_length=100)),
                ('iucn_status', models.CharField(blank=True, help_text='Estado IUCN: EX, EW, CR, EN, VU, NT, LC, DD', max_length=10, null=True)),
                ('descripcion', models.JSONField(blank=True, default=dict, help_text='Descripción en múltiples idiomas obtenida de Wikipedia')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('image_source', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Especie',
                'verbose_name_plural': 'Especies',
                'ordering': ['scientific_name'],
            },
        ),
        migrations.CreateModel(
            name='Avistamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha en que se vio la especie')),
                ('lugar', models.CharField(help_text='Lugar del avistamiento', max_length=255)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, help_text='Foto opcional tomada por el usuario', null=True, upload_to='avistamientos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avistamientos', to=settings.AUTH_USER_MODEL)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avistamientos', to='atlas.especie')),
            ],
            options={
                'verbose_name': 'Avistamiento',
                'verbose_name_plural': 'Avistamientos',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(help_text='Código ISO 3166-1 Alpha-2 (ES, FR, AQ...)', max_length=2, unique=True)),
                ('latitud', models.FloatField(help_text='Latitud del centro del país')),
                ('longitud', models.FloatField(help_text='Longitud del centro del país')),
                ('descripcion', models.TextField(blank=True)),
                ('continente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paises', to='atlas.continente')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EspeciePais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('image_source', models.CharField(blank=True, max_length=50, null=True)),
                ('primera_vez', models.DateTimeField(auto_now_add=True, help_text='Fecha del primer registro en este país')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especie_paises', to='atlas.especie')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especie_paises', to='atlas.pais')),
            ],
            options={
                'verbose_name': 'Especie en País',
                'verbose_name_plural': 'Especies en Países',
                'ordering': ['especie__scientific_name'],
            },
        ),
        migrations.AddField(
            model_name='especie',
            name='paises',
            field=models.ManyToManyField(blank=True, related_name='especies', through='atlas.EspeciePais', to='atlas.pais'),
        ),
        migrations.CreateModel(
            name='BioLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biolog_entries', to=settings.AUTH_USER_MODEL)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biolog_entries', to='atlas.especie')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biolog_entries', to='atlas.pais')),
            ],
            options={
                'verbose_name': 'Mi Atlas',
                'verbose_name_plural': 'Mi Atlas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Gratuito'), ('premium', 'Premium')], default='free', max_length=20)),
                ('estado', models.CharField(choices=[('active', 'Activa'), ('cancelled', 'Cancelada'), ('expired', 'Expirada')], default='active', max_length=20)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, help_text='Fecha de expiración del plan premium', null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='atlas.especie')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'ordering': ['-created_at'],
                'unique_together': {('usuario', 'especie')},
            },
        ),
        migrations.AddIndex(
            model_name='especiepais',
            index=models.Index(fields=['pais'], name='atlas_espec_pais_id_1318e3_idx'),
        ),
        migrations.AddIndex(
            model_name='especiepais',
            index=models.Index(fields=['especie'], name='atlas_espec_especie_f69b04_idx'),
        ),
        migrations.AddIndex(
            model_name='especiepais',
            index=models.Index(fields=['pais', 'especie'], name='atlas_espec_pais_id_470a41_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='especiepais',
            unique_together={('especie', 'pais')},
        ),
        migrations.AddIndex(
            model_name='especie',
            index=models.Index(fields=['species_key'], name='atlas_espec_species_b31615_idx'),
        ),
        migrations.AddIndex(
            model_name='especie',
            index=models.Index(fields=['scientific_name'], name='atlas_espec_scienti_6c5157_idx'),
        ),
        migrations.AddIndex(
            model_name='especie',
            index=models.Index(fields=['canonical_name'], name='atlas_espec_canonic_ce8c16_idx'),
        ),
        migrations.AddIndex(
            model_name='especie',
            index=models.Index(fields=['kingdom'], name='atlas_espec_kingdom_45cc2c_idx'),
        ),
        migrations.AddIndex(
            model_name='especie',
            index=models.Index(fields=['family'], name='atlas_espec_family_1e8108_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='biolog',
            unique_together={('usuario', 'especie', 'pais')},
        ),
    ]
