# Generated by Django 6.0.3 on 2026-03-20 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecieTerritorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('image_source', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlas.especie')),
            ],
            options={
                'verbose_name': 'Especie-Territorio',
                'verbose_name_plural': 'Especies-Territorio',
            },
        ),
        migrations.CreateModel(
            name='TerritorioEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('continente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='territorios', to='atlas.continente')),
                ('especies', models.ManyToManyField(blank=True, related_name='territorios', through='atlas.EspecieTerritorio', to='atlas.especie')),
            ],
            options={
                'verbose_name': 'Territorio Especial',
                'verbose_name_plural': 'Territorios Especiales',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='especieterritorio',
            name='territorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlas.territorioespecial'),
        ),
        migrations.AlterUniqueTogether(
            name='especieterritorio',
            unique_together={('especie', 'territorio')},
        ),
    ]
