# Generated by Django 6.0.3 on 2026-04-22 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0002_especieterritorio_territorioespecial_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizPartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(default=0)),
                ('racha_maxima', models.IntegerField(default=0)),
                ('preguntas_total', models.IntegerField(default=0)),
                ('aciertos', models.IntegerField(default=0)),
                ('dificultad', models.CharField(choices=[('facil', 'Fácil'), ('normal', 'Normal'), ('dificil', 'Difícil')], default='normal', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_partidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partida Quiz',
                'verbose_name_plural': 'Partidas Quiz',
                'ordering': ['-puntuacion'],
            },
        ),
    ]
